export { default as Favorite } from './favorite';
export { default as Home } from './home';
export { default as Login } from './login';
export { default as Movies } from './movies';
export { default as Movie } from './movie';
export { default as Register } from './register';
export { default as Search } from './search';
export { default as TvShows } from './tv-shows';
export { default as TvShow } from './tv-show';
